name: Azure Pipelines
variables:
  python.version: '3.7.6'
trigger:
- main  # Change this to your desired trigger branch

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run starterapis.json'
        workingDirectory: '$(System.DefaultWorkingDirectory)'